RetailApp/RetailApp/Controllers/PrizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RetailApp.Database;

namespace RetailApp.Controllers
{
    public class PrizeController : Controller
    {
        //
        // GET: /Prize/

        public ActionResult Index(String Token)
        {
            if (Token == null)
            {
                Token = Request.Cookies["Token"].Value; 
            }
            using (var csx = new RetailAppEntities())
            {
                USER u = csx.USER.SingleOrDefault(user => user.Token == Token);
                ViewBag.Profile = u;
                csx.Entry(u).State = System.Data.Entity.EntityState.Modified;
                u.Status = 6;
                u.Fecha = DateTime.Now;
                csx.SaveChanges();
                PRICES p = csx.PRICES.SingleOrDefault(price => price.PerfilVIP == u.Perfil);
                ViewBag.Price = p;
            }
            return View();
        }      
    } 
        
}

RetailApp/RetailApp/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RetailApp.Database;

namespace RetailApp.Controllers
{
    public class QuestionnaireController : Controller
    {
        //
        // GET: /Questionnaire/

        public ActionResult Index()
        {

            using (var csx = new RetailAppEntities())
            {
                List<PREGUNTA> l = csx.PREGUNTA.ToList();
                ViewBag.quest = l;

                List<OPCION> h = csx.OPCION.ToList();
                ViewBag.opcs = h;

                String CookieVal = Request.Cookies["Token"].Value; 
                String email = csx.USER.SingleOrDefault(user => user.Token == CookieVal).Email;
                ViewBag.email = email;
            }
            return View();    
            }
      
        }
    }

RetailApp/RetailApp/Views/Questionnaire/Index.cshtml
@{
    ViewBag.Title = "Questionnaire";
}
@using RetailApp.Database; 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>

    <!-- Icon -->
    <link rel="icon" href="../Content/Media/Img/icon_gA.png" type="image/png">

    <!-- Bootstrap -->
    <link href="@Url.Content("~/Content/Media/Bootstrap/css/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/Media/Bootstrap/css/bootstrap-theme.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/Media/css/questionnaire.css")" rel="stylesheet" />

    <script src="../Content/Media/JQuery/jquery-2.1.3.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="../Content/Media/Bootstrap/js/questionnaire.js"></script>
    <script type="text/javascript" src="../Content/Media/Bootstrap/js/fbLogin.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <style>
        
        /*  SPINNER  */
        .board {
            position:relative;
        }

        #spinner {
            display:none;
            position:absolute;
            z-index:1000;
            top:0;
            left:0;
            height:100%;
            width:100%;
            background:rgba(255,255,255, .8)
                       url("../../Content/Media/Img/spinner.gif")
                       50% 50%
                       no-repeat;
        }

        div.loading {
            overflow:hidden;
        }

        div.loading #spinner {
            display:block;
        }
    </style>
    <div id="email_hidden" style="display:none" >@ViewBag.email</div>
    <section style="background: url(../Img/Discover.png) no-repeat fixed center; height:100% ">
        <div class="container">
            <div class="row">
                <div class="board">
                    <div id="spinner"></div>
                    <!--<div class="board-header">
                        <h3 style="text-align:center;">Retail Event Questionnaire</h3>
                    </div>     -->
                    <div class="tab-content">
                        @{
                            var claseDefault = "tab-pane fade";
                        }
                        @foreach (PREGUNTA preg in (List<PREGUNTA>)ViewBag.quest)
                        {
                            if (preg.Id == 1)
                            {
                                claseDefault = "tab-pane fade in active";
                            }
                            else
                            {
                                claseDefault = "tab-pane fade";
                            }
                            <div class="@claseDefault" id="@("question"+preg.Id)">

                                <div class="question-header">
                                    <h1>@preg.Pregunta1</h1>
                                </div>
                                <div class="question-choices">
                                    @foreach (OPCION opc in (List<OPCION>)ViewBag.opcs)
                                    {
                                        if (opc.Id == preg.Id)
                                        {
                                            <div class="choice">
                                                <input class="radio" type="radio" name="choice" value="@opc.Numero" />
                                                <label>@opc.Descripcion</label>
                                            </div>
                                        }
                                    }
                                </div>
                            </div>
                        }
                        <div id="send-button" class='text-center'>
                            <form action="@Url.Action("Index","Prize")" method="post">
                                <input type="submit" value="Enviar" class="send-button" />
                                <input type="hidden" name="Token" value="@Request.Cookies["Token"].Value" />
                            </form>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <div class="board-inner">
                        <ul class="nav nav-tabs" id="myTab">
                            <div class="liner"></div>
                            <li class="active">
                                <a id="tab1" data-toggle="tab" title="Category 1" href="#question1">
                                    <span id="roundtab1" class="round-tabs">
                                        1
                                    </span>
                                </a>
                            </li>

                            <li>
                                <a id="tab2" title="Category 2">
                                    <span id="roundtab2" class="round-tabs">
                                        2
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a id="tab3" title="Category 3">
                                    <span id="roundtab3" class="round-tabs">
                                        3
                                    </span>
                                </a>
                            </li>

                            <li>
                                <a id="tab4" title="Category 4">
                                    <span id="roundtab4" class="round-tabs">
                                        4
                                    </span>
                                </a>
                            </li>

                            <li>
                                <a id="tab5" title="Category 5">
                                    <span id="roundtab5" class="round-tabs">
                                        5
                                    </span>
                                </a>
                            </li>

                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </section>

   @*<div>
        @RenderBody()
    </div>*@

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/Content/Media/Bootstrap/js/bootstrap.min.js"></script>

</body>
</html>